name: Keep Streamlit Apps Alive

on:
  schedule:
    - cron: '0 5 * * *'
    - cron: '0 11 * * *'
    - cron: '0 17 * * *'
    - cron: '0 23 * * *'

  workflow_dispatch:

jobs:
  ping-apps:
    runs-on: ubuntu-latest

    steps:
      - name: Send request to rubenxi-website.streamlit.app
        run: curl -s -o /dev/null -w "%{http_code}\n" https://rubenxi-website.streamlit.app/
